### ISSUE TITLE
Survey list vs. Survey title naming

### ISSUE THREAD

**Issue by swacsa** [SenseNet/sn-surveyeditor#1]
Hi!

I created a workspace, and allowed the "Survey List" content type.
I went into the workpsce, and int the create NEW list there are no Survey List, just Survey Title. 
It should be good if the names would be the same

![suervey list vs title](https://cloud.githubusercontent.com/assets/11719551/25387987/d2a50774-29cc-11e7-83e8-94d0681df448.png)

**Comment by tusmester** [comment]
You can see two types of things in the New menu:
- content types, like Folder
- content templates: if a type has a template in _/Root/contentteplates_, you will see those templates in the list _instead of the type_ itself. In your case I guess you see the template for the survey type - you can change the display name of that template manually.

**Comment by swacsa** [comment]
Done, thanks!
![survey_list_rename](https://cloud.githubusercontent.com/assets/11719551/25389874/0f36f896-29d2-11e7-9324-a3145c4ce871.png)
